### CoVaricane & CorRelation

In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv("PrePlacement.csv")

In [3]:
dataset

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,0.0
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,215,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,0.0

In [5]:
# Check any NA values
dataset.isna().sum()

sl_no             0
gender            0
ssc_p             0
ssc_b             0
hsc_p             0
hsc_b             0
hsc_s             0
degree_p          0
degree_t          0
workex            0
etest_p           0
specialisation    0
mba_p             0
status            0
salary            0
dtype: int64

In [6]:
# Check any null values
dataset.isnull().sum()

sl_no             0
gender            0
ssc_p             0
ssc_b             0
hsc_p             0
hsc_b             0
hsc_s             0
degree_p          0
degree_t          0
workex            0
etest_p           0
specialisation    0
mba_p             0
status            0
salary            0
dtype: int64

In [17]:
# dir(dataset)
dataset.drop(columns=["sl_no", "gender", "ssc_b", "hsc_b", "hsc_s", "degree_t", "workex", "specialisation", "status"], axis=1, inplace=True)
dataset.cov()

,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
ssc_p,117.228377,58.853253,42.702550,37.659225,24.535952,9.088585e+05
hsc_p,58.853253,112.063731,33.684453,33.838355,21.517688,7.310079e+05
degree_p,42.702550,33.684453,53.604710,22.078774,17.185200,4.663363e+05
etest_p,37.659225,33.838355,22.078774,176.251018,16.886973,3.727004e+05
mba_p,24.535952,21.517688,17.185200,16.886973,34.028376,1.239934e+05
salary,908858.485818,731007.850848,466336.264888,372700.449468,123993.387361,2.259185e+10

In [22]:
# CoVariance between Degree vs Entrance Test Marks
# The cov between degree and enterance test is 22.078774
# Its indicates that two columns that are degree_p and etest_p in a positive linear relationship
# That means if a student get higher marks in Degree he/she will get higher marks in Entrance test as well and vice versa.

In [19]:
# CoVariance between Entrance Test Marks vs MBA Marks
# The cov between etest_p and mba_p is 16.886973
# This is also indicate the positive linear relationship.

### Correlation

In [21]:
dataset.corr()

             ssc_p     hsc_p  degree_p   etest_p     mba_p    salary
ssc_p     1.000000  0.513478  0.538686  0.261993  0.388478  0.558475
hsc_p     0.513478  1.000000  0.434606  0.240775  0.348452  0.459424
degree_p  0.538686  0.434606  1.000000  0.227147  0.402376  0.423762
etest_p   0.261993  0.240775  0.227147  1.000000  0.218055  0.186775
mba_p     0.388478  0.348452  0.402376  0.218055  1.000000  0.141417
salary    0.558475  0.459424  0.423762  0.186775  0.141417  1.000000

In [23]:
# Correlation between MBA and Salary
# Correlation between MBA_Marks and Salary is 0.141417
# It's indicate that positive linear relationship between two columns (mba_p and salary)
# But the value 0.141417 is too poor
# MBA is nearly 0.14% influence in salary (indirectly saying other factors determine the salary than MBA) for this dataset