### Measures of Central Tendency (Coursework)
- Mean (Average value)
- Median (Mid point of the ordered dataset)
- Mode (Most frequent value)

Its a univariate analysis. No need other columns support.

In [1]:
import pandas as pd

In [2]:
dataset = pd.read_csv("Placement.csv")

In [3]:
dataset

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,215,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN

In [4]:
dataset.columns

Index(['sl_no', 'gender', 'ssc_p', 'ssc_b', 'hsc_p', 'hsc_b', 'hsc_s',
       'degree_p', 'degree_t', 'workex', 'etest_p', 'specialisation', 'mba_p',
       'status', 'salary'],
      dtype='object')

In [5]:
dataset["hsc_s"].value_counts()

Commerce    113
Science      91
Arts         11
Name: hsc_s, dtype: int64

In [7]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 15 columns):
sl_no             215 non-null int64
gender            215 non-null object
ssc_p             215 non-null float64
ssc_b             215 non-null object
hsc_p             215 non-null float64
hsc_b             215 non-null object
hsc_s             215 non-null object
degree_p          215 non-null float64
degree_t          215 non-null object
workex            215 non-null object
etest_p           215 non-null float64
specialisation    215 non-null object
mba_p             215 non-null float64
status            215 non-null object
salary            148 non-null float64
dtypes: float64(6), int64(1), object(8)
memory usage: 25.3+ KB

In [26]:
dataset["ssc_p"].mean()

67.30339534883721

In [27]:
dataset["ssc_p"].median()

67.0

In [28]:
dataset["ssc_p"].mode()

0    62.0
dtype: float64

In [24]:
dataset["ssc_p"].mode()[0]

62.0

In [30]:
dataset.describe()
# It will show only for numerical data (Since its applicable for numbers)

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
count,215.000000,215.000000,215.000000,215.000000,215.000000,215.000000,148.000000
mean,108.000000,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
std,62.209324,10.827205,10.897509,7.358743,13.275956,5.833385,93457.452420
min,1.000000,40.890000,37.000000,50.000000,50.000000,51.210000,200000.000000
25%,54.500000,60.600000,60.900000,61.000000,60.000000,57.945000,240000.000000
50%,108.000000,67.000000,65.000000,66.000000,71.000000,62.000000,265000.000000
75%,161.500000,75.700000,73.000000,72.000000,83.500000,66.255000,300000.000000
max,215.000000,89.400000,97.700000,91.000000,98.000000,77.890000,940000.000000

In [31]:
# pd.DataFrame() ==> Assist to create a table
# If no data passed, it will create an empty table
descriptive = pd.DataFrame()

In [32]:
descriptive

Empty DataFrame
Columns: []
Index: []

In [33]:
descriptive = pd.DataFrame(index=["Mean", "Median", "Mode"])

In [34]:
descriptive

Empty DataFrame
Columns: []
Index: [Mean, Median, Mode]

In [38]:
from Univariate import Univariate 

qual, quan = Univariate.get_qual_quan(dataset)

In [40]:
quan

['sl_no', 'ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p', 'salary']

In [48]:
descriptive = pd.DataFrame(
    index=["Mean", "Median", "Mode"],
    columns=quan
)

In [49]:
descriptive

       sl_no ssc_p hsc_p degree_p etest_p mba_p salary
Mean     NaN   NaN   NaN      NaN     NaN   NaN    NaN
Median   NaN   NaN   NaN      NaN     NaN   NaN    NaN
Mode     NaN   NaN   NaN      NaN     NaN   NaN    NaN

In [50]:
# C => R (think the alphabet order) Column => Row
descriptive["hsc_p"]["Mean"]

nan

In [51]:
descriptive["hsc_p"]["Mean"] = 0

# Read the location again
descriptive["hsc_p"]["Mean"]

0

In [52]:
descriptive

       sl_no ssc_p hsc_p degree_p etest_p mba_p salary
Mean     NaN   NaN     0      NaN     NaN   NaN    NaN
Median   NaN   NaN   NaN      NaN     NaN   NaN    NaN
Mode     NaN   NaN   NaN      NaN     NaN   NaN    NaN

In [53]:
quan

['sl_no', 'ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p', 'salary']

In [75]:
descriptive = pd.DataFrame(
    index=["Mean", "Median", "Mode"],
    columns=quan
)

In [76]:
descriptive

       sl_no ssc_p hsc_p degree_p etest_p mba_p salary
Mean     NaN   NaN   NaN      NaN     NaN   NaN    NaN
Median   NaN   NaN   NaN      NaN     NaN   NaN    NaN
Mode     NaN   NaN   NaN      NaN     NaN   NaN    NaN

In [77]:
for column in quan:
    descriptive[column]["Mean"] = dataset[column].mean()

In [78]:
descriptive

       sl_no    ssc_p    hsc_p degree_p  etest_p    mba_p  salary
Mean     108  67.3034  66.3332  66.3702  72.1006  62.2782  288655
Median   NaN      NaN      NaN      NaN      NaN      NaN     NaN
Mode     NaN      NaN      NaN      NaN      NaN      NaN     NaN

In [79]:
for column in quan:
    descriptive[column]["Mean"] = dataset[column].mean()
    descriptive[column]["Median"] = dataset[column].median()

In [80]:
descriptive

       sl_no    ssc_p    hsc_p degree_p  etest_p    mba_p  salary
Mean     108  67.3034  66.3332  66.3702  72.1006  62.2782  288655
Median   108       67       65       66       71       62  265000
Mode     NaN      NaN      NaN      NaN      NaN      NaN     NaN

In [83]:
for column in quan:
    descriptive[column]["Mean"] = dataset[column].mean()
    descriptive[column]["Median"] = dataset[column].median()
    descriptive[column]["Mode"] = dataset[column].mode()

In [84]:
descriptive

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
Mean,108,67.3034,66.3332,66.3702,72.1006,62.2782,288655
Median,108,67,65,66,71,62,265000
Mode,0 1 1 2 2 3 3 4 4 ...,0 62.0 dtype: float64,0 63.0 dtype: float64,0 65.0 dtype: float64,0 60.0 dtype: float64,0 56.7 dtype: float64,0 300000.0 dtype: float64

In [85]:
for column in quan:
    descriptive[column]["Mean"] = dataset[column].mean()
    descriptive[column]["Median"] = dataset[column].median()
    descriptive[column]["Mode"] = dataset[column].mode()[0]

In [87]:
descriptive

       sl_no    ssc_p    hsc_p degree_p  etest_p    mba_p  salary
Mean     108  67.3034  66.3332  66.3702  72.1006  62.2782  288655
Median   108       67       65       66       71       62  265000
Mode       1       62       63       65       60     56.7  300000

In [ ]:
# Please find the assignment in the same repo: Central-Tendency-Assignment.docx